default:
	echo "Run encode, crack, decode, with the following syntax: [command]..."
encode:
	@javac encode.java
	@java encode.java $(ARGS)
decode:
	@javac decode.java
	@java decode.java $(ARGS)

crack:
	@javac crack.java
	@java crack $(ARGS)
